# NOTE
# - USE ABSOLUTE PATHS, possibly with `_quarto.yml.local`, when relative ones are not working (due
#   to e.g. a soft link to the `code` directory).

project:
  title: "Building on open source tools for targeted and untargeted metabolomics and exposomics"
  execute-dir: project
  output-dir: "../../reports"

lang: en
date: today
date-format: full
toc: true
number-sections: true
bibliography: "bibliography.bib"
tbl-cap-location: top

format:
  html: 
    css: "styles.css"
    toc-depth: 3
    code-fold: true
    toc-location: left
    embed-resources: true
    page-layout: full

    fig-width : 10
    fig-height: 6
    out-width: "100%"
    fig-align: "default"

execute:
  echo: true
  output: asis
  warning: false    # No warning

knitr:
  opts_knit:
    root.dir: "../../"
  opts_chunk:
    purl: false      # Most of the code are not to be extracted.
    message: false    # All messages are ignored.
    
    # fig.path: "../outputs/figures/"

    R.options: 
      xfun.cache_rds.clean: false     # Keep old even after invalidated
      
      knitr.kable.NA: ""         # NA is shown as "" in kable
      # Otherwise, full width tables are shown no matter what the setting is for `kable`.
      knitr.table.html.attr: 'data-quarto-disable-processing = "true"'
      kable_styling_full_width: false   # No more `kable_styling(full_with = FALSE)`
      
      width: 100     # Text (markup) output

