title: EXPO_00019 (Quant neg) - vIS
input_file: Input_data/EXPO_00019/neg/EXPO_00019_for_Quant_Neg_vIS.txt
intermediate_dir: data/intermediate
table_dir: data/processed
concentration_unit: g/L
user: Roxana Merino (NFEx / SP)
university: KI - Karolisnka Institutet
project_title: 'HEAP - sewage water '
free_text: |
  HEAP_sewage_water_Quant_neg
