---
title: "Report on"
format:
  pdf:
    classoption: landscape
    geometry:
      - top=30mm
      - left=20mm
      - heightrounded
---

```{r}
#| label: 'setup'
#| purl: true
# The preprocessed data used for calibration. Default is `loess_norm`.
if (!exists("DATA_ID")) DATA_ID <- "loess_norm"

# Load packages and project local libraries
options(box.path = "code/")           # Path to project local libraries
box::use(
  SumExp,           # Light SummarizedExperiment, `[`
  projlib/msdial,     # Handle MS-Dial files
  projlib/show,       # Functions to present data
  io = projlib/check_io_exist,       # Check input/output files
  patchwork,           # Combine ggplot objects. `+`
  ggplot2[...],        # Too long to write and usually specific enough
  ggfortify,           # PCA plot (autoplot)
)
# Read `params.yml` to get various project parameters
params <- yaml::read_yaml("params.yml")

# Input/Output files
FILE <- list(
  i = rlang::list2(
    proc = msdial$get_sumexp_file_name(params, "proc"),
    qc = msdial$get_sumexp_file_name(params, "qc_steps"),   # Intermediate state of the data
  )
)
# Check if input files and output directories exist
io$check_io_exist(FILE)

concn_se <- readRDS(FILE$i$proc)[[DATA_ID]]
FEATURE_IDS <- SumExp::rownames(concn_se)[1:2]
# Load the intermediate data during QC
qc_steps <- readRDS(FILE$i$qc)
stopifnot("Preprocessing was not completed." = qc_steps[["Preprocessing Completed"]])
# Conversion tables
sample_id_name_tbl <- qc_steps[["sample_id_name_tbl"]]
feature_id_name_tbl <- qc_steps[["feature_id_name_tbl"]]
```

# Project Information

* User: `r params$user`
* University: `r params$university`
* Project: `r params$project_title`

`r params$free_text`

{{< pagebreak >}}

# General overview

* Number of samples: `r ncol(concn_se)`
* Number of targeted features: `r nrow(concn_se)`

{{< pagebreak >}}

## PCA

```{r}
#| label: 'pca'
#| fig-width: 15
#| fig-height: 8
#| out-width: '100%'

plot_pca <- function(se, mat_id) {
  mat <- t(se[[mat_id]])
  mat <- mat[, colSums(mat, na.rm = TRUE) > 0]       # Scale is not possible with all zeros
  mat <- mat[, apply(mat, 2, var, na.rm = TRUE) > 0]        # Remove constant rows
  pca_res <- stats::prcomp(mat, scale. = TRUE)
  
  se_df <- SumExp::col_df(se)      # `data` in ggplot2::autoplot
  # Plot
  ggplot2::autoplot(pca_res, data = se_df, colour = "Class")
}
p1 <- qc_steps[["Normalized"]][, quote(! contr_cat %in% c("QC", "CalCurve", "Blank"))] |> 
  plot_pca(DATA_ID) + ggtitle("Target + Non-target")
p2 <- plot_pca(concn_se[, quote(contr_cat != "QC")], DATA_ID) +
  ggtitle("Target")
p1 + p2 + patchwork::plot_layout(guides = "collect")
```

{{< pagebreak >}}

## Feature summary

```{r}
#| label: 'features-summary'

# Information about the features
features <- SumExp::row_df(concn_se) |> 
  tibble::as_tibble(rownames = "feature_id")
# Concentration
mat <- concn_se[["conc"]]
# Summary about the concentration ranges
conc_summary <- tibble::tibble(
  feature_id = features$feature_id,
  llod = features$llod,
  df_n = sapply(1:nrow(mat), \(i) sum(mat[i, ] >= llod[i])),
  df_perc = df_n / ncol(mat) * 100,
  median = apply(mat, 1, median),
  mean = rowMeans(mat),
  min = apply(mat, 1, min),
  max = apply(mat, 1, max),
)
conc_summary <- conc_summary |> 
  dplyr::mutate(
    df_perc = scales::percent(df_perc / 100),
    median = round(median, 2),
    mean = round(mean, 2),
    min = round(min, 2),
    max = round(max, 2)
  )
# Summary about the calibration curve models
model_summary <- qc_steps[[DATA_ID]][["calcurve_models"]] |> 
  lapply(\(m) {
    type <- m$best_model_name
    R2 <- round(m$R2s[[type]], 3)
    n_conc <- m$n_conc
    data.frame(R2, type, n_conc) 
  }) |> 
  purrr::list_rbind(names_to = "feature_id")
# Merge
summary_tbl <- list(
  features[, c("feature_id", "feature_name")],
  conc_summary,
  model_summary
) |> 
  purrr::reduce(dplyr::full_join, by = "feature_id") |> 
  dplyr::arrange(feature_name) |> 
  dplyr::select(
    "Feature" = feature_name,
    "LLOD" = llod,
    "DF (%)" = df_perc,
    "Median" = median,
    "Average" = mean,
    "Min" = min,
    "Max" = max,
    "R2" = R2,
    "Model" = type,
    "N of points" = n_conc,
  )

# Summary table
summary_tbl |> 
  knitr::kable(caption = "Summary of Features") |> 
  kableExtra::kable_styling(
    latex_options = "striped", 
    full_width = FALSE, 
    repeat_header_continued = TRUE,
  ) |> 
  kableExtra::footnote(
    general = "DF: Detection frequency (percentage of samples above LLOD)",
    footnote_as_chunk = TRUE
  )
```

{{< pagebreak >}}

# Invidual features

{{< pagebreak >}}

```{r}
#| label: 'individual-features'
#| fig-width: 12
#| fig-height: 8
#| out-height: '95%'
calcurve_se <- qc_steps[[DATA_ID]][["calcurve_se within range"]]
calcurve_models <- qc_steps[[DATA_ID]][["calcurve_models"]]
for(feature_i in FEATURE_IDS) {
  feature_name <- feature_id_name_tbl$feature_name[feature_id_name_tbl$feature_id == feature_i]
  cat("\n\n## ", feature_name, "\n")
  
  x_se <- concn_se[rownames(concn_se) == feature_i, quote(! contr_cat %in% c("QC", "Blank"))]
  cc_se <- calcurve_se[rownames(calcurve_se) == feature_i, ]
  # Calibration curves
  p1 <- show$ggplot_calcurve_samples(x_se, 
                                     cc_se, 
                                     calcurve_models, 
                                     mat_id = DATA_ID) +
    labs(
      title = "Linear scale",
      y = "Peak area (Normalized)"
    )
  p2 <- p1 + scale_x_log10() + scale_y_log10() + 
    labs(title = "Log10 scale")
  # Distirbution of the concentration by class
  x_df <- SumExp::as_tibble(x_se)
  p3 <- ggplot(x_df) +
    geom_boxplot(aes(x = Class, y = conc, color = Class, fill = Class)) +
    labs(
      x = show$label_if_has(x_df$Class, "Class"),
      y = show$label_if_has(x_df$conc, "Concentration"),
    ) +
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) +    # Vertical x-axis
    theme(legend.position = "none") +      # No legend
    scale_y_log10()
  # Text
  mdl <- calcurve_models[[feature_i]]
  fts <- SumExp::row_df(x_se)
  conc <- x_se[["conc"]][1, ]
  text_df <- tibble::tibble(
    x = 0,
    y = 0.5,
    label = paste0(
      "Best model: ", mdl$best_model_name, "\n\n",
      "R2: ", round(summary(mdl$inv_model)$r.squared, 3), "\n\n",
      "N of points: ", mdl$n_conc, "\n\n",
      "DF (%): ", scales::percent(sum(conc >= fts$llod) / length(conc)), "\n\n",
      "LLOD: ", fts$llod, "\n\n",
      "LLOQ: ", fts$lloq, "\n\n",
      ""         # For trailing comma
    )
  )
  text1 <- ggplot(text_df) +
    ggtext::geom_textbox(
      aes(x, y, label = label),
      box.color = "black",
      width = unit(10, "cm"),
      fill = NA,
      hjust = 0,
      vjust = 0.5,
      size = 5
    ) +
    scale_x_continuous(limits = c(0, 1), expand = c(0, 0)) +
    scale_y_continuous(limits = c(0, 1), expand = c(0, 0)) +
    theme_void()
  
  # Plot
  design <- "
    1122
    1122
    3#44
  "
  print(p1 + p2 + p3 + text1 + patchwork::plot_layout(design = design, guides = "collect"))
}
```

