channels:
  - conda-forge
  - bioconda
dependencies:
  - quarto

  - r-base
  # R env
  - r-tidyverse
  - r-box
  - r-roxygen2      # `box` requires this.

  # Plots
  - r-labelled              # labelled
  - r-patchwork
  - r-ggfortify
  - r-ggtext
  - r-plotly

  # Rmarkdown
  - r-english
  - r-kableextra
  - r-janitor
  - r-codetools             # For `cache` in Qmd

  - r-shiny
  - r-shinyfiles
  - r-quarto

