channels:
  - conda-forge
  - bioconda
dependencies:
  - quarto=1.5.57
  - bioconductor-tidysummarizedexperiment

  # bioconductor-tidysummarizedexperiment [1.10.0|1.12.0] would require
  # │  └─ r-base >=4.3,<4.4.0a0 , which can be installed;
  - r-base=4.3.3
  # R env
  - r-tidyverse=2.0.0
  - r-box=1.2.0
  - r-roxygen2=7.3.2      # `box` requires this.

  # Rmarkdown
  - r-english
  - r-kableextra
  - r-janitor
  - r-gridextra>=2.3
  - r-codetools             # For `cache` in Qmd

  - r-shiny>=1.9.1
  - r-shinyfiles
  - r-quarto>=1.4.4

