
The concentration of the samples has been computed using the calibration curve in the [section above](#calibration).
The distribution of the concentration of the samples is shown below.

```{r}
#| fig-width: 12
#| fig-height: 10
show_df <- SumExp::as_tibble(measurements_se)
ggplot(show_df) +
  geom_boxplot(aes(x = sample_name, y = conc, fill = Class)) +
  labs(
    title = "Concentration distribution by sample", 
    x = labelled::get_label_attribute(show_df$sample_name),
    y = labelled::get_label_attribute(show_df$conc),
  ) +
  # Turn the x-axis title to vertical
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  scale_y_log10()
```

```{r}
#| fig-width: 12
#| fig-height: 20
ggplot(show_df) +
  geom_boxplot(aes(x = chem_name, y = conc)) +
  labs(
    title = "Concentration distribution by chemical", 
    x = labelled::get_label_attribute(show_df$chem_name),
    y = labelled::get_label_attribute(show_df$conc),
  ) +
  # Turn the x-axis title to vertical
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  scale_y_log10() + 
  facet_grid(Class~.)
```
